spring:
  datasource:
    username: root
    password: 1210
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.100.81.172:3306/yang_blog?serverTimezone=UTC&useSSL=false
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 39.100.81.172
    password:
